"""add postgres table and column comments

Revision ID: 20260330_0003
Revises: 20260329_0002
Create Date: 2026-03-30 10:30:00
"""

from alembic import op
import sqlalchemy as sa

revision = "20260330_0003"
down_revision = "20260329_0002"
branch_labels = None
depends_on = None

TIMESTAMP_COLUMNS = {
    "created_at": "记录创建时间。",
    "updated_at": "记录最后更新时间。",
}

TABLE_COMMENTS = {
    "users": "用户账号表。来源：/api/register/ 注册接口；消费：/api/token 登录鉴权。",
    "api_providers": "外部模型供应商配置表。来源：/api/providers/ 与初始化脚本；消费：analyzer 问答与知识抽取、preprocessor 的 VLM/LLM 配置解析。",
    "llm_models": "可用模型目录表。来源：模型管理接口与初始化脚本；消费：问答接口、知识抽取任务、preprocessor 模型选择。",
    "prompts": "提示词主表。来源：提示词管理接口与编辑器；消费：prompt_manager、prompt_validator 以及 preprocessor 各步骤任务。",
    "prompt_versions": "提示词版本表。来源：提示词版本创建与编辑；消费：提示词加载、版本校验与回溯。",
    "tenants": "租户主表。来源：平台运营配置；消费：内容源、源文档、考试会话等业务数据的租户隔离。",
    "content_sources": "题库内容来源表。来源：/api/question-bank/sources/；消费：source_documents 建档与试卷来源类型回填。",
    "source_documents": "题库源文档表。来源：/api/question-bank/documents/upload 与建档接口；消费：题库解析任务、考试会话的原始来源关联。",
    "document_parse_jobs": "源文档解析阶段流水表。来源：QuestionBankIngestionService 各阶段作业；消费：源文档详情查询与排障。",
    "assets": "通用素材资产表。来源：题库文档抽图、题目插图提取与考试题目截图挂接；消费：公式、题块、考试题图等多处外键引用。",
    "papers": "结构化试卷主表。来源：题库文档解析入库；消费：题号映射、匹配结果归属试卷以及后续试卷治理。",
    "paper_sections": "试卷分区表。来源：解析器预留的试卷结构分区；消费：后续分区展示与题型统计。",
    "question_families": "题目家族表。来源：题目治理与聚类归并；消费：question_items 家族归属与策略卡复用。",
    "question_items": "标准题目主表。来源：题库解析 persist_questions；消费：检索、试题匹配、作答判定和后续诊断。",
    "paper_questions": "试卷题号到标准题的映射表。来源：题库解析；消费：匹配结果回溯到具体试卷及题号。",
    "formulas": "公式结构化表。来源：题目文本中的公式抽取；消费：题块/选项公式引用、公式治理与渲染。",
    "question_blocks": "题目块表。来源：题库解析对题干、答案、解析等内容切块；消费：检索文档构建、结构化展示与标签抽取。",
    "question_options": "选择题选项表。来源：题库解析写入；消费：前端展示、正确答案判定与公式挂接。",
    "taxonomy_nodes": "知识分类节点表。来源：知识体系治理；消费：题目标注、学情画像与知识树展示。",
    "strategy_cards": "策略卡表。来源：题型方法论治理；消费：题族归纳、学情建议与解题指导。",
    "mistake_patterns": "错因模式表。来源：错因治理维护；消费：学情诊断、错因归类与纠偏建议。",
    "question_tag_links": "题目标签关联表。来源：标签抽取或人工审核；消费：知识点归因、检索过滤与画像聚合。",
    "question_relations": "题目关系边表。来源：相似题或变式题挖掘；消费：推荐、组卷与迁移练习。",
    "retrieval_documents": "检索文档分片表。来源：题目结构化内容切分；消费：向量化、全文索引与题目匹配召回。",
    "embedding_points": "向量索引映射表。来源：检索文档入向量库后回写；消费：索引审计、重建与清理。",
    "exam_sessions": "考试会话主表。来源：考试会话创建接口与 preprocessor bundle 导入；消费：匹配任务、学情分析与结果展示。",
    "exam_session_questions": "考试会话题目识别表。来源：试卷导入时逐题写入；消费：题库匹配、人工复核与命中结果展示。",
    "question_match_results": "考试题目与题库题目的候选匹配结果表。来源：自动匹配服务；消费：匹配视图、人工审核与命中回填。",
    "student_attempts": "学生作答记录表。来源：考试会话导入时生成；消费：正确性判定、错因分析和学情汇总。",
    "diagnosis_snapshots": "学情诊断快照表。来源：后续诊断任务生成；消费：学情报告展示、能力画像与行动建议。",
}

COLUMN_COMMENTS = {
    "users": {
        "id": "用户主键 ID。",
        "phone_number": "登录手机号，系统内唯一。",
        "hashed_password": "经过哈希处理的登录密码。",
        "is_active": "账号是否启用。",
        **TIMESTAMP_COLUMNS,
    },
    "api_providers": {
        "id": "供应商主键 ID。",
        "name": "供应商名称，系统内唯一。",
        "api_url": "供应商 API 基础地址。",
        "encrypted_api_key": "加密后的 API Key。",
        **TIMESTAMP_COLUMNS,
    },
    "llm_models": {
        "id": "模型主键 ID。",
        "name": "模型名称，例如 qwen-vl-plus。",
        "provider_id": "所属供应商 ID，关联 api_providers.id。",
        **TIMESTAMP_COLUMNS,
    },
    "prompts": {
        "id": "提示词主键 ID。",
        "name": "提示词内部唯一名称。",
        "display_name": "提示词展示名称。",
        "description": "提示词用途说明。",
        "pipeline_step": "所属流程步骤编号。",
        "category": "提示词分类。",
        "target_type": "提示词面向对象类型。",
        "scenario": "提示词适用场景。",
        "version": "当前主版本号。",
        "is_latest": "是否为当前最新版本标识。",
        "is_active": "是否启用。",
        "created_by": "创建人。",
        **TIMESTAMP_COLUMNS,
    },
    "prompt_versions": {
        "id": "提示词版本主键 ID。",
        "prompt_id": "所属提示词 ID，关联 prompts.id。",
        "version": "版本号。",
        "prompt_text": "提示词正文内容。",
        "status": "版本状态，例如 published。",
        "created_by": "版本创建人。",
        "created_at": "版本创建时间。",
        "change_log": "本次版本变更说明。",
    },
    "tenants": {
        "id": "租户主键 ID。",
        "tenant_name": "租户名称，系统内唯一。",
        "tenant_type": "租户类型，例如学校或机构。",
        "status": "租户状态。",
        **TIMESTAMP_COLUMNS,
    },
    "content_sources": {
        "id": "内容来源主键 ID。",
        "tenant_id": "所属租户 ID；为空表示平台级来源。",
        "source_name": "来源名称。",
        "source_type": "来源类型，例如真题、教辅、题库包。",
        "provider_name": "外部提供方名称。",
        "commercial_allowed": "是否允许商业使用。",
        "ai_processing_allowed": "是否允许 AI 处理。",
        "training_allowed": "是否允许用于训练。",
        "license_scope": "授权范围 JSON。",
        "expires_at": "授权到期时间。",
        "remark": "补充备注。",
        **TIMESTAMP_COLUMNS,
    },
    "source_documents": {
        "id": "源文档主键 ID。",
        "source_id": "所属内容来源 ID，关联 content_sources.id。",
        "tenant_id": "所属租户 ID；为空表示平台共享文档。",
        "file_name": "原始文件名。",
        "file_ext": "文件扩展名。",
        "mime_type": "文件 MIME 类型。",
        "storage_url": "原始文件存储路径或 URL。",
        "file_sha256": "原始文件 SHA256 哈希。",
        "normalized_docx_url": "归一化后的 DOCX 路径。",
        "normalized_pdf_url": "归一化后的 PDF 路径。",
        "parse_profile": "解析配置档位。",
        "subject": "文档所属学科。",
        "grade": "文档适用年级。",
        "year": "年份。",
        "region": "地区。",
        "title": "文档标题。",
        "visibility_scope": "可见范围。",
        "parse_status": "解析状态。",
        **TIMESTAMP_COLUMNS,
    },
    "document_parse_jobs": {
        "id": "解析作业主键 ID。",
        "source_document_id": "所属源文档 ID，关联 source_documents.id。",
        "job_stage": "解析阶段，例如 normalize、segment、index。",
        "tool_name": "执行该阶段的工具名称。",
        "model_name": "执行该阶段使用的模型名称。",
        "input_version": "输入版本标识。",
        "output_location": "阶段输出文件位置。",
        "status": "作业状态。",
        "metrics_json": "阶段指标 JSON。",
        "error_message": "失败错误信息。",
        "started_at": "开始时间。",
        "ended_at": "结束时间。",
    },
    "assets": {
        "id": "资产主键 ID。",
        "tenant_id": "所属租户 ID；为空表示平台共享素材。",
        "owner_type": "所属对象类型，例如 source_document、question_item、exam_question。",
        "owner_id": "所属对象主键 ID。",
        "asset_role": "资产角色，例如 figure、question_crop。",
        "storage_url": "素材存储路径或 URL。",
        "thumbnail_url": "缩略图路径或 URL。",
        "page_no": "素材所在页码。",
        "width": "素材宽度。",
        "height": "素材高度。",
        "bbox": "素材在原页面中的边界框 JSON。",
        "ocr_text": "素材 OCR 文本。",
        "caption_text": "素材说明或标题文本。",
        "file_hash": "素材文件哈希。",
        "phash": "素材感知哈希。",
        **TIMESTAMP_COLUMNS,
    },
    "papers": {
        "id": "试卷主键 ID。",
        "source_document_id": "来源源文档 ID，关联 source_documents.id。",
        "title": "试卷标题。",
        "subject": "试卷学科。",
        "grade": "试卷年级。",
        "year": "试卷年份。",
        "region": "试卷地区。",
        "stream_type": "文理科或流派类型。",
        "exam_type": "考试类型。",
        "source_type": "来源类型，从 content_sources 透传。",
        "total_questions": "试卷题目总数。",
        "raw_outline_json": "试卷原始结构大纲 JSON。",
        "is_canonical": "是否为标准基准试卷。",
        "review_status": "审核状态。",
        **TIMESTAMP_COLUMNS,
    },
    "paper_sections": {
        "id": "试卷分区主键 ID。",
        "paper_id": "所属试卷 ID，关联 papers.id。",
        "section_order": "分区顺序。",
        "section_name": "分区名称。",
        "section_type": "分区类型。",
        "start_question_no": "起始题号。",
        "end_question_no": "结束题号。",
    },
    "question_families": {
        "id": "题族主键 ID。",
        "subject": "题族所属学科。",
        "family_name": "题族名称。",
        "core_pattern": "核心题型模式描述。",
        "core_strategy_id": "核心策略卡 ID，关联 strategy_cards.id。",
        "core_intent_summary": "核心意图摘要。",
        "gaokao_frequency": "高考出现频次。",
        "region_stats_json": "地区统计 JSON。",
        "year_stats_json": "年份统计 JSON。",
        **TIMESTAMP_COLUMNS,
    },
    "question_items": {
        "id": "标准题主键 ID。",
        "tenant_id": "所属租户 ID；为空表示平台共享题目。",
        "subject": "题目学科。",
        "grade": "题目适用年级。",
        "question_type": "题目类型。",
        "stem_plain_text": "题干原始纯文本。",
        "stem_normalized_text": "题干归一化文本，用于去噪和匹配。",
        "answer_text": "标准答案文本。",
        "solution_summary": "解题思路摘要。",
        "difficulty": "难度系数。",
        "has_formula": "是否包含公式。",
        "has_figure": "是否包含图形。",
        "family_id": "题族 ID，关联 question_families.id。",
        "quality_score": "题目质量评分。",
        "source_origin": "来源方式，例如 explicit。",
        "review_status": "审核状态。",
        "canonical_hash": "题目归一化去重哈希。",
        **TIMESTAMP_COLUMNS,
    },
    "paper_questions": {
        "id": "试卷题号映射主键 ID。",
        "paper_id": "所属试卷 ID，关联 papers.id。",
        "question_item_id": "关联标准题 ID，关联 question_items.id。",
        "question_no": "题号。",
        "sub_question_no": "小题号。",
        "display_order": "展示顺序。",
        "score_value": "题目分值。",
        "page_no": "所在页码。",
        "anchor_bbox": "题号或题目定位框 JSON。",
        "source_question_label": "源文档中的题目标记。",
        "parse_confidence": "题号映射解析置信度。",
    },
    "formulas": {
        "id": "公式主键 ID。",
        "question_item_id": "所属标准题 ID，关联 question_items.id。",
        "block_id": "所属题块 ID，关联 question_blocks.id。",
        "source_type": "公式来源类型，例如 text、image。",
        "latex_text": "LaTeX 公式文本。",
        "mathml_text": "MathML 公式文本。",
        "linear_text": "线性化公式文本。",
        "normalized_signature": "归一化公式签名，用于比对去重。",
        "parse_confidence": "公式解析置信度。",
        "asset_id": "关联资产 ID，关联 assets.id。",
    },
    "question_blocks": {
        "id": "题块主键 ID。",
        "question_item_id": "所属标准题 ID，关联 question_items.id。",
        "block_order": "题块顺序。",
        "block_role": "题块角色，例如 stem、answer、analysis。",
        "content_format": "内容格式，例如 text、json。",
        "text_content": "题块纯文本内容。",
        "rich_content_json": "富文本或结构化内容 JSON。",
        "formula_id": "关联公式 ID，关联 formulas.id。",
        "asset_id": "关联资产 ID，关联 assets.id。",
        "parent_block_id": "父题块 ID，关联 question_blocks.id。",
        "source_origin": "题块来源方式。",
        "confidence": "题块抽取置信度。",
        "is_primary": "是否为该角色主块。",
    },
    "question_options": {
        "id": "选项主键 ID。",
        "question_item_id": "所属标准题 ID，关联 question_items.id。",
        "option_key": "选项标识，例如 A、B、C。",
        "option_text": "选项文本。",
        "formula_id": "关联公式 ID，关联 formulas.id。",
        "asset_id": "关联资产 ID，关联 assets.id。",
        "display_order": "展示顺序。",
        "is_correct": "是否为正确选项。",
    },
    "taxonomy_nodes": {
        "id": "知识分类节点主键 ID。",
        "taxonomy_type": "分类体系类型。",
        "code": "节点编码。",
        "name": "节点名称。",
        "parent_id": "父节点 ID，关联 taxonomy_nodes.id。",
        "path": "节点路径。",
        "subject": "所属学科。",
        "grade_scope": "适用年级范围。",
        "description": "节点说明。",
        "status": "节点状态。",
        **TIMESTAMP_COLUMNS,
    },
    "strategy_cards": {
        "id": "策略卡主键 ID。",
        "code": "策略卡编码。",
        "name": "策略卡名称。",
        "subject": "所属学科。",
        "applicable_question_types": "适用题型 JSON。",
        "trigger_signals": "触发信号 JSON。",
        "thinking_steps": "思考步骤 JSON。",
        "common_mistakes": "常见错误 JSON。",
        "short_tip": "一句话提示。",
        "detail_content": "详细内容。",
        "source_origin": "来源方式。",
        "review_status": "审核状态。",
        **TIMESTAMP_COLUMNS,
    },
    "mistake_patterns": {
        "id": "错因模式主键 ID。",
        "code": "错因编码。",
        "name": "错因名称。",
        "category": "错因类别。",
        "description": "错因描述。",
        "symptom_signals": "症状信号 JSON。",
        "correction_advice": "纠偏建议。",
        "source_origin": "来源方式。",
        "review_status": "审核状态。",
        **TIMESTAMP_COLUMNS,
    },
    "question_tag_links": {
        "id": "题目标签关联主键 ID。",
        "question_item_id": "所属标准题 ID，关联 question_items.id。",
        "target_type": "关联目标类型，例如 taxonomy_node、mistake_pattern。",
        "target_id": "关联目标主键 ID。",
        "relation_type": "关联关系类型。",
        "source_origin": "标签来源方式。",
        "confidence": "关联置信度。",
        "evidence_block_id": "证据题块 ID，关联 question_blocks.id。",
        "approved_status": "审核状态。",
    },
    "question_relations": {
        "id": "题目关系主键 ID。",
        "source_question_id": "源标准题 ID，关联 question_items.id。",
        "target_question_id": "目标标准题 ID，关联 question_items.id。",
        "relation_type": "关系类型，例如 similar、variant。",
        "score": "关系强度得分。",
        "evidence_json": "关系证据 JSON。",
        **TIMESTAMP_COLUMNS,
    },
    "retrieval_documents": {
        "id": "检索文档主键 ID。",
        "tenant_id": "所属租户 ID；为空表示平台共享检索文档。",
        "entity_type": "来源实体类型，例如 question_stem、question_answer。",
        "entity_id": "来源实体主键 ID。",
        "text_for_bm25": "供全文检索使用的文本。",
        "text_for_embedding": "供向量化使用的文本。",
        "metadata_json": "检索附加元数据 JSON。",
        "is_active": "当前文档是否有效。",
        "content_hash": "文档内容哈希。",
        "updated_at": "检索文档最后更新时间。",
    },
    "embedding_points": {
        "id": "向量点映射主键 ID。",
        "retrieval_document_id": "所属检索文档 ID，关联 retrieval_documents.id。",
        "backend_type": "向量后端类型，例如 qdrant、chroma。",
        "point_id": "向量库中的点 ID。",
        "model_name": "生成向量使用的模型名称。",
        "vector_dim": "向量维度。",
        "content_hash": "入库时的内容哈希。",
        **TIMESTAMP_COLUMNS,
    },
    "exam_sessions": {
        "id": "考试会话主键 ID。",
        "tenant_id": "所属租户 ID；为空表示平台级测试数据。",
        "student_id": "学生 ID。",
        "source_document_id": "关联源文档 ID，指向原始试卷或题库来源。",
        "matched_paper_id": "自动匹配命中的试卷 ID，关联 papers.id。",
        "exam_date": "考试日期。",
        "subject": "考试学科。",
        "parse_status": "试卷解析状态。",
        "matching_status": "题库匹配状态。",
        "analysis_status": "学情分析状态。",
        "visibility_scope": "可见范围。",
        **TIMESTAMP_COLUMNS,
    },
    "exam_session_questions": {
        "id": "考试题主键 ID。",
        "exam_session_id": "所属考试会话 ID，关联 exam_sessions.id。",
        "source_question_no": "原试卷题号。",
        "question_item_id": "命中的标准题 ID，关联 question_items.id。",
        "page_no": "题目所在页码。",
        "question_crop_asset_id": "题目截图资产 ID，关联 assets.id。",
        "recognized_text": "识别出的题目文本。",
        "parse_confidence": "题目识别置信度。",
        "match_confidence": "题库匹配置信度。",
        "review_status": "当前复核状态。",
    },
    "question_match_results": {
        "id": "匹配候选主键 ID。",
        "exam_question_id": "所属考试题 ID，关联 exam_session_questions.id。",
        "candidate_question_id": "候选标准题 ID，关联 question_items.id。",
        "match_type": "匹配类型，例如 hybrid_recall。",
        "text_score": "文本相似度得分。",
        "vector_score": "向量相似度得分。",
        "formula_score": "公式相似度得分。",
        "final_score": "综合得分。",
        "accepted": "是否被接受为最终命中结果。",
        **TIMESTAMP_COLUMNS,
    },
    "student_attempts": {
        "id": "作答记录主键 ID。",
        "exam_session_id": "所属考试会话 ID，关联 exam_sessions.id。",
        "exam_question_id": "所属考试题 ID，关联 exam_session_questions.id。",
        "question_item_id": "匹配到的标准题 ID，关联 question_items.id。",
        "student_id": "学生 ID。",
        "student_answer_raw": "学生原始答案文本。",
        "answer_blocks_json": "答案块及来源图片等结构化信息 JSON。",
        "is_correct": "是否判定正确。",
        "score_earned": "学生得分。",
        "time_spent_seconds": "作答耗时，单位秒。",
        "teacher_mark_json": "教师批注与批改结果 JSON。",
        "ocr_confidence": "答案 OCR 置信度。",
        **TIMESTAMP_COLUMNS,
    },
    "diagnosis_snapshots": {
        "id": "诊断快照主键 ID。",
        "student_id": "学生 ID。",
        "exam_session_id": "所属考试会话 ID，关联 exam_sessions.id。",
        "knowledge_profile_json": "知识掌握画像 JSON。",
        "ability_profile_json": "能力画像 JSON。",
        "mistake_profile_json": "错因画像 JSON。",
        "action_plan_json": "行动建议 JSON。",
        "llm_summary": "LLM 生成的总结文本。",
        "generated_at": "快照生成时间。",
    },
}


def _sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _comment_on_table(table_name: str, comment: str) -> None:
    op.execute(sa.text(f'COMMENT ON TABLE "{table_name}" IS {_sql_literal(comment)}'))


def _comment_on_column(table_name: str, column_name: str, comment: str) -> None:
    op.execute(sa.text(f'COMMENT ON COLUMN "{table_name}"."{column_name}" IS {_sql_literal(comment)}'))


def _clear_table_comment(table_name: str) -> None:
    op.execute(sa.text(f'COMMENT ON TABLE "{table_name}" IS NULL'))


def _clear_column_comment(table_name: str, column_name: str) -> None:
    op.execute(sa.text(f'COMMENT ON COLUMN "{table_name}"."{column_name}" IS NULL'))


def upgrade() -> None:
    for table_name, comment in TABLE_COMMENTS.items():
        _comment_on_table(table_name, comment)

    for table_name, columns in COLUMN_COMMENTS.items():
        for column_name, comment in columns.items():
            _comment_on_column(table_name, column_name, comment)


def downgrade() -> None:
    for table_name, columns in COLUMN_COMMENTS.items():
        for column_name in columns:
            _clear_column_comment(table_name, column_name)

    for table_name in TABLE_COMMENTS:
        _clear_table_comment(table_name)
